export const actionTypes = {
  ADD_TO_LIST_REQUESTING: "ADD_TO_LIST_REQUESTING",
  ADD_TO_LIST_SUCCESS: "ADD_TO_LIST_SUCCESS",
  ADD_TO_LIST_ERROR: "ADD_TO_LIST_ERROR",
  EDIT_TO_LIST_REQUESTING: "EDIT_TO_LIST_REQUESTING",
  EDIT_TO_LIST_SUCCESS: "EDIT_TO_LIST_SUCCESS",
  EDIT_TO_LIST_ERROR: "EDIT_TO_LIST_ERROR",
  GET_DATA_REQUESTING: "GET_DATA_REQUESTING",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  GET_DATA_ERROR: "GET_DATA_ERROR",
  EDIT_CHECK_SUCCESS: "EDIT_CHECK_SUCCESS",
};
